In [26]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 

In [27]:
df = pd.read_csv("healthcare_dataset.csv")
df_backup = df.copy()

In [28]:
df.dropna(inplace=True) # Delete Rows Have Nun Values

In [29]:
import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

In [30]:
df["Gender"]= df["Gender"].replace({"Female": 0,"Male" : 1})
print(df.head())

            Name  Age Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30      1         B-            Cancer        2024-01-31   
1   LesLie TErRy   62      1         A+           Obesity        2019-08-20   
2    DaNnY sMitH   76      0         A-           Obesity        2022-09-22   
3   andrEw waTtS   28      0         O+          Diabetes        2020-11-18   
4  adrIENNE bEll   43      0        AB+            Cancer        2022-09-19   

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross   
1   Samantha Davies                     Kim Inc           Medicare   
2  Tiffany Mitchell                    Cook PLC              Aetna   
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare   
4    Kathleen Hanna                 White-White              Aetna   

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306          

In [32]:
print(df['Admission Type'].unique())
df['Admission Type']=df['Admission Type'].replace({'Urgent':0,'Emergency':1,'Elective':2})

[0 1 2]


In [34]:
print(df["Medication"].nunique())
print(df["Medication"].unique())
df["Medication"] = df["Medication"].replace({"Paracetamol":0,"Ibuprofen" :1,"Aspirin":2 ,"Penicillin": 3,"Lipitor": 4})

5
[0 1 2 3 4]


In [36]:
print(df["Test Results"].unique())
df["Test Results"]= df["Test Results"].replace({"Normal": 0,"Inconclusive": 1,"Abnormal": 2})


[0 1 2]


In [38]:
print(df["Medical Condition"].unique())
df["Medical Condition"] = df["Medical Condition"].replace({"Cancer":0,"Obesity":1,"Diabetes":2,
  "Asthma":3,"Hypertension":4,"Arthritis":5})

[0 1 2 3 4 5]


In [40]:
print(df["Blood Type"].unique())
df["Blood Type"] = df["Blood Type"].replace({"A+":0,"A-":1,"B+":2,"B-":3,"AB+":4,"AB-":5,"O+":6,"O-":7})

[3 0 1 6 4 5 2 7]


In [42]:
print(df["Insurance Provider"].unique()) 
df["Insurance Provider"] = df["Insurance Provider"].replace({"Blue Cross":0,"Medicare":1,"Aetna":2,"UnitedHealthcare":3,"Cigna":4})

[0 1 2 3 4]


In [44]:
df.head()
print(df.tail())

                    Name  Age Gender Blood Type Medical Condition  \
55495  eLIZABeTH jaCkSOn   42      0          6                 3   
55496         KYle pEREz   61      0          5                 1   
55497       HEATher WaNG   38      0          2                 4   
55498     JENniFER JOneS   43      1          7                 5   
55499       jAMES GARCiA   53      0          6                 5   

      Date of Admission           Doctor                      Hospital  \
55495        2020-08-16    Joshua Jarvis                Jones-Thompson   
55496        2020-01-23  Taylor Sullivan                  Tucker-Moyer   
55497        2020-07-13   Joe Jacobs DVM  and Mahoney Johnson Vasquez,   
55498        2019-05-25   Kimberly Curry      Jackson Todd and Castro,   
55499        2024-04-02    Dennis Warren                Henry Sons and   

      Insurance Provider  Billing Amount  Room Number Admission Type  \
55495                  0     2650.714952          417              2

In [46]:
print(df.info())
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Name                55500 non-null  object 
 1   Age                 55500 non-null  int64  
 2   Gender              55500 non-null  object 
 3   Blood Type          55500 non-null  object 
 4   Medical Condition   55500 non-null  object 
 5   Date of Admission   55500 non-null  object 
 6   Doctor              55500 non-null  object 
 7   Hospital            55500 non-null  object 
 8   Insurance Provider  55500 non-null  object 
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64  
 11  Admission Type      55500 non-null  object 
 12  Discharge Date      55500 non-null  object 
 13  Medication          55500 non-null  object 
 14  Test Results        55500 non-null  object 
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4

In [18]:
df.drop(columns=['Name','Doctor','Hospital',], inplace=True) # Delete all rows whose type is not number 


In [47]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission']) # Convert date in Date of Admission to int
df['Date_of_admission'] = (df['Date of Admission'] - pd.Timestamp('2000-01-01')).dt.days
df.drop(columns=['Date of Admission'], inplace=True)


In [48]:
df['Discharge Date'] = pd.to_datetime(df['Discharge Date']) # Convert date in Discharge Date to int
df['Discharge_date'] = (df['Discharge Date'] - pd.Timestamp('2000-01-01')).dt.days
df.drop(columns=['Discharge Date'], inplace=True)

In [52]:
print(df.dtypes) 

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Medication             object
Test Results           object
Date_of_admission       int64
Discharge_date          int64
dtype: object


In [22]:
X = df.drop("Medical Condition",axis=1) # featuers : المميزات
y = df["Medical Condition"] # Target : الهدف

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2,random_state=100
)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# Algorithm Nearest Neighbors
knn = KNeighborsClassifier(n_neighbors=10) # انشاء النموذج *اقرب 10 اشخاص
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test) # التنبؤ على بيانات الاختبار
accuracy = accuracy_score(y_test, y_pred) # حساب الدقة
correct_predictions = (y_pred == y_test).sum()
print("Number of correct predictions:", correct_predictions)

print("Accuracy:", accuracy)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
X = X_train[:100]
y = y_train[:100]
from sklearn.svm import SVC# Algorithm RBF SVM
from sklearn.metrics import  accuracy_score
svm_rbf = SVC(kernel="rbf")
svm_rbf.fit(X,y)
y_pred_svm_rbf = svm_rbf.predict(X_test)
acc_svm_rbf = accuracy_score(y_test,y_pred_svm_rbf)
correct_predictions = (y_pred_svm_rbf == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_svm = " ,acc_svm_rbf)


Number of correct predictions: 1837
Accuracy_svm =  0.1654954954954955


In [ ]:
X = X_train[:100]
y = y_train[:100]
from sklearn.gaussian_process import GaussianProcessClassifier #Algorithm Gaussian Process
gp = GaussianProcessClassifier()
gp.fit(X,y)
y_pred_gp = gp.predict(X_test)
acc_gp = accuracy_score(y_test,y_pred_gp)
correct_predictions = (y_pred_gp == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_gp = ",acc_gp)

Number of correct predictions: 1768
Accuracy_gp =  0.1592792792792793


In [ ]:
from sklearn.tree import DecisionTreeClassifier # Algorithm Decision Tree
from sklearn.metrics import  accuracy_score
tree = DecisionTreeClassifier()
tree.fit(X_train,y_train)
y_pred_tree = tree.predict(X_test)
acc_tree = (y_test,y_pred_tree)
correct_predictions = (y_pred_tree == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_Tree = ",acc_tree)


Number of correct predictions: 3158
Accuracy_Tree =  (51251    4
37449    0
2884     3
26889    2
30431    4
        ..
14229    4
46396    3
1647     1
20050    2
28775    5
Name: Medical Condition, Length: 11100, dtype: int64, array([4, 1, 1, ..., 2, 3, 1], shape=(11100,)))


In [ ]:
from sklearn.ensemble import RandomForestClassifier # Algorithm Random Forest
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred_rf = rf.predict(X_test)
acc_rf = (y_test,y_pred_rf)
correct_predictions = (y_pred_rf == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_RF = ",acc_rf)

Number of correct predictions: 3300
Accuracy_RF =  (51251    4
37449    0
2884     3
26889    2
30431    4
        ..
14229    4
46396    3
1647     1
20050    2
28775    5
Name: Medical Condition, Length: 11100, dtype: int64, array([4, 4, 0, ..., 4, 0, 3], shape=(11100,)))


In [ ]:
from sklearn.neural_network import MLPClassifier # Algorithm Neural Net
nn = MLPClassifier(max_iter=500) # اقصى عدد لللفات او التكرارات يمر فيها النموذج للتعلم
nn.fit(X_train,y_train)
y_pred_nn = nn.predict(X_test)
acc_nn = (y_test,y_pred_nn)
correct_predictions = (y_pred_nn == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_nn = ",acc_nn)

Number of correct predictions: 1907
Accuracy_nn =  (51251    4
37449    0
2884     3
26889    2
30431    4
        ..
14229    4
46396    3
1647     1
20050    2
28775    5
Name: Medical Condition, Length: 11100, dtype: int64, array([4, 0, 4, ..., 4, 4, 0], shape=(11100,)))


In [ ]:
from sklearn.ensemble import AdaBoostClassifier # Algorithm AdaBoost
ada = AdaBoostClassifier()
ada.fit(X_train,y_train)
y_pred_ada = ada.predict(X_test)
acc_ada = (y_test,y_pred_ada)
correct_predictions = (y_pred_ada == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_ada = ",acc_ada)


Number of correct predictions: 1764
Accuracy_ada =  (51251    4
37449    0
2884     3
26889    2
30431    4
        ..
14229    4
46396    3
1647     1
20050    2
28775    5
Name: Medical Condition, Length: 11100, dtype: int64, array([5, 5, 5, ..., 5, 5, 5], shape=(11100,)))


In [ ]:
from sklearn.naive_bayes import GaussianNB # Algorithm Naive Bayes
nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred_nb = nb.predict(X_test)
acc_nb = (y_test,y_pred_nb)
correct_predictions = (y_pred_nb == y_test).sum()
print("Number of correct predictions:", correct_predictions)
print("Accuracy_nb = ",acc_nb)

Number of correct predictions: 1869
Accuracy_nb =  (51251    4
37449    0
2884     3
26889    2
30431    4
        ..
14229    4
46396    3
1647     1
20050    2
28775    5
Name: Medical Condition, Length: 11100, dtype: int64, array([0, 4, 5, ..., 2, 5, 5], shape=(11100,)))
